[input]
# input_root = "/Users/allenzhou/ALICE/alidata/hyperloop_res/femtoep/OO/AnalysisResults_3d_25ae_pass2.root"
input_root = "/Users/allenzhou/ALICE/alidata/hyperloop_res/femtoep/OO/AnalysisResults_3d_25ae_pass2_sel8.root"
# input_root = "/Users/allenzhou/ALICE/alidata/hyperloop_res/femtoep/OO/AnalysisResults_3d_25ae_pass2_small.root"
task_name = "femto-dream-pair-task-track-track"
same_event_subtask = "SameEvent_3Dqn"
mixed_event_subtask = "MixedEvent_3Dqn"
sparse_object_name = "relPair3dRmTMultPercentileQnPairphi"

[output]
output_directory = "/Users/allenzhou/ALICE/alidata/femtoep_res/OO"
cf_root_name = "EP_dependence_CF_3d_25ae_pass2_sel8_3phi.root"
# cf_root_name = "EP_dependence_CF_3d_25ae_pass2.root"
# cf_root_name = "EP_dependence_CF_3d_25ae_pass2_small.root"
# fit_root_name = "EP_dependence_CF_full_fit_v2_3d_25ae_pass2.root"
# fit_root_name = "EP_dependence_CF_full_fit_v2_3d_25ae_pass2_nonfold.root"
# fit_root_name = "EP_dependence_CF_full_fit_v2_3d_25ae_pass2_nonfold_nocol.root"
fit_root_name = "EP_dependence_CF_full_fit_v2_3d_25ae_pass2_nonfold_fcoul_sel8_3phi.root"
# fit_root_name = "EP_dependence_CF_full_fit_v2_3d_25ae_pass2_nonfold_fcoul.root"
# fit_root_name = "EP_dependence_CF_full_fit_v2_3d_25ae_pass2_small_nonfold.root"
# fit_summary_name = "3d_25ae_pass2_fit_summary_nonfold.tsv"
# fit_summary_name = "3d_25ae_pass2_fit_summary_nonfold_nocol.tsv"
# fit_summary_name = "3d_25ae_pass2_fit_summary_nonfold_fcoul.tsv"
fit_summary_name = "3d_25ae_pass2_fit_summary_nonfold_fcoul_sel8_3phi.tsv"
fit_report_directory = "/Users/allenzhou/Research_software/Code_base/Exp_femto_3d/res"
# fit_report_root_name = "fit_report_3d_25ae_pass2.root"
# fit_report_root_name = "fit_report_3d_25ae_pass2_nonfold.root"
# fit_report_root_name = "fit_report_3d_25ae_pass2_nonfold_nocol.root"
# fit_report_root_name = "fit_report_3d_25ae_pass2_nonfold_fcoul.root"
fit_report_root_name = "fit_report_3d_25ae_pass2_nonfold_fcoul_sel8_3phi.root"
# fit_report_root_name = "fit_report_3d_25ae_pass2_small_nonfold.root"
log_level = "warn"

[build]
# map_pair_phi_to_symmetric_range = true
map_pair_phi_to_symmetric_range = false
write_normalized_se_me_1d_projections = false
reopen_output_file_per_slice = false
split_mixed_event_by_phi = true


[build.rebin.phi]
enabled = true
factor = 6

[build.rebin.mt]
enabled = true

[fit.parameters.alpha]
fixed_value = 2.0


[fit]
model = "full"
coulomb_mode = "finite_source"
# coulomb_mode = "none"|"gamow"|"finite_source"
finite_source_mode = "iterative_1d"
# finite_source_mode = "fixed_1d"|"iterative_1d"
use_core_halo_lambda = true
use_q2_baseline = true
use_pml = true
fit_q_max = 0.15
# omit to follow the input CF metadata written by build-cf
map_pair_phi_to_symmetric_range = false
# map_pair_phi_to_symmetric_range = true

[[bins.centrality]]
min = 0
max = 10

[[bins.centrality]]
min = 10
max = 30

[[bins.centrality]]
min = 30
max = 50

[[bins.centrality]]
min = 50
max = 80

[[bins.centrality]]
min = 80
max = 100


# [[bins.mt]]
# min = 0.2
# max = 0.4

[[bins.mt]]
min = 0.4
max = 0.6

[[bins.mt]]
min = 0.6
max = 0.8

[[bins.mt]]
min = 0.8
max = 1.1

[[bins.mt]]
min = 1.1
max = 1.6

# [[bins.mt]]
# min = 2.005
# max = 2.504

# [[bins.mt]]
# min = 2.504
# max = 3.003

# [[bins.mt]]
# min = 3.003
# max = 4.002

# [[bins.mt]]
# min = 4.002
# max = 5.002

# [[bins.mt]]
# min = 5.002
# max = 8.001

[[fit_selection.centrality]]
min = 0
max = 10

[[fit_selection.centrality]]
min = 10
max = 30

[[fit_selection.centrality]]
min = 30
max = 50


# [[fit_selection.mt]]
# min = 0.2
# max = 0.4

[[fit_selection.mt]]
min = 0.4
max = 0.6

[[fit_selection.mt]]
min = 0.6
max = 0.8

[[fit_selection.mt]]
min = 0.8
max = 1.1

[[fit_selection.mt]]
min = 1.1
max = 1.6
