[input]
input_root = "/Users/allenzhou/ALICE/alidata/hyperloop_res/femtoep/OO/AnalysisResults_3d_25ae_pass2_merged.root"
task_name = "femto-dream-pair-task-track-track"
same_event_subtask = "SameEvent_3Dqn"
mixed_event_subtask = "MixedEvent_3Dqn"
sparse_object_name = "relPair3dRmTMultPercentileQnPairphi"

[output]
output_directory = "/Users/allenzhou/ALICE/alidata/femtoep_res/OO"
cf_root_name = "EP_dependence_CF_3d_25ae_pass2.root"
fit_root_name = "EP_dependence_CF_full_fit_v2_3d_25ae_pass2_nonfold.root"
fit_summary_name = "3d_25ae_pass2_fit_summary_nonfold.tsv"
log_level = "warn"

[build]
map_pair_phi_to_symmetric_range = false
write_normalized_se_me_1d_projections = false
reopen_output_file_per_slice = false

[fit]
model = "full"
use_coulomb = true
use_core_halo_lambda = true
use_q2_baseline = true
use_pml = true
fit_q_max = 0.15
# omit to follow the input CF metadata written by build-cf
map_pair_phi_to_symmetric_range = false

[[bins.centrality]]
min = 0
max = 10

[[bins.centrality]]
min = 10
max = 30

[[bins.centrality]]
min = 30
max = 50

[[bins.centrality]]
min = 50
max = 80

[[bins.centrality]]
min = 80
max = 100

[[bins.mt]]
min = 0.0
max = 0.519

[[bins.mt]]
min = 0.519
max = 0.812

[[bins.mt]]
min = 0.812
max = 1.208

[[bins.mt]]
min = 1.208
max = 1.606

[[bins.mt]]
min = 1.606
max = 2.005

[[bins.mt]]
min = 2.005
max = 2.504

[[bins.mt]]
min = 2.504
max = 3.003

[[bins.mt]]
min = 3.003
max = 4.002

[[bins.mt]]
min = 4.002
max = 5.002

[[bins.mt]]
min = 5.002
max = 8.001

[[fit_selection.centrality]]
min = 0
max = 10

[[fit_selection.centrality]]
min = 10
max = 30

[[fit_selection.centrality]]
min = 30
max = 50


[[fit_selection.mt]]
min = 0.0
max = 0.519

[[fit_selection.mt]]
min = 0.519
max = 0.812

[[fit_selection.mt]]
min = 0.812
max = 1.208

[[fit_selection.mt]]
min = 1.208
max = 1.606
